import type { Meditation } from "./types";

const mk = (m: Omit<Meditation, "id" | "access" | "publishedAt"> & Partial<Pick<Meditation, "access">>): Meditation => ({
  id: `med-${m.slug}`,
  access: "member",
  publishedAt: "2026-08-01",
  ...m,
});

export const meditations: Meditation[] = [
  mk({
    slug: "intencion-del-dia",
    title: "Intención del día",
    description: "Diez minutos para elegir cómo quieres sentirte hoy antes de que el día decida por ti.",
    videoId: "m-morning-1",
    instructorId: "sofi",
    moment: "morning",
    feelings: ["claridad", "volver-a-ti"],
    duration: 10,
    featured: true,
    access: "free",
  }),
  mk({
    slug: "energia-para-comenzar",
    title: "Energía para comenzar",
    description: "Respiración activa y visualización corta para arrancar con foco.",
    videoId: "m-morning-2",
    instructorId: "sofi",
    moment: "morning",
    feelings: ["confianza"],
    duration: 5,
  }),
  mk({
    slug: "soltar-el-dia",
    title: "Soltar el día",
    description: "Un cierre consciente: agradece lo que pasó, suelta lo que no fue tuyo.",
    videoId: "m-night-1",
    instructorId: "sofi",
    moment: "night",
    feelings: ["soltar", "gratitud"],
    duration: 15,
    featured: true,
  }),
  mk({
    slug: "para-dormir-profundo",
    title: "Para dormir profundo",
    description: "Relajación progresiva del cuerpo para llegar al sueño sin esfuerzo.",
    videoId: "m-night-2",
    instructorId: "sofi",
    moment: "night",
    feelings: ["ansiedad", "soltar"],
    duration: 20,
  }),
  mk({
    slug: "volver-al-presente",
    title: "Volver al presente",
    description: "Para momentos de estrés: anclas sensoriales y respiración 4-7-8.",
    videoId: "m-stress-1",
    instructorId: "sofi",
    moment: "stress",
    feelings: ["estres", "ansiedad", "volver-a-ti"],
    duration: 10,
    featured: true,
    access: "free",
  }),
  mk({
    slug: "pausa-de-cinco",
    title: "Pausa de cinco",
    description: "Cinco minutos entre reuniones para calmar la mente.",
    videoId: "m-stress-2",
    instructorId: "sofi",
    moment: "stress",
    feelings: ["estres", "claridad"],
    duration: 5,
  }),
  mk({
    slug: "abrirte-a-recibir",
    title: "Abrirte a recibir",
    description: "Abundancia y gratitud: una práctica para confiar en que hay suficiente.",
    videoId: "m-abund-1",
    instructorId: "sofi",
    moment: "abundance",
    feelings: ["abundancia", "gratitud"],
    duration: 15,
  }),
  mk({
    slug: "confianza-en-ti",
    title: "Confianza en ti",
    description: "Reconecta con tu voz interna y con decisiones que se sienten tuyas.",
    videoId: "m-conf-1",
    instructorId: "sofi",
    moment: "other",
    feelings: ["confianza", "claridad"],
    duration: 10,
  }),
  mk({
    slug: "amor-propio",
    title: "Amor propio",
    description: "Veinte minutos para hablarte como le hablarías a alguien que amas.",
    videoId: "m-amor-1",
    instructorId: "sofi",
    moment: "other",
    feelings: ["amor-propio", "volver-a-ti"],
    duration: 20,
    featured: true,
  }),
];

export const meditationBySlug = (slug: string) => meditations.find((m) => m.slug === slug);
