import type { Talk } from "./types";

export const talks: Talk[] = [
  {
    id: "talk-nutricion",
    slug: "comer-sin-culpa",
    title: "Comer sin culpa: alimentación intuitiva",
    description:
      "Cómo salir del ciclo de dietas y construir una relación tranquila con la comida, con herramientas concretas para la semana.",
    expertId: "exp-nutricion",
    specialty: "Nutrición clínica",
    category: "nutricion",
    videoId: "t-nutri",
    durationMin: 42,
    access: "member",
    featured: true,
    isNew: true,
    publishedAt: "2026-09-10",
  },
  {
    id: "talk-autoestima",
    slug: "limites-y-autoestima",
    title: "Límites y autoestima",
    description: "Por qué decir que no es una forma de cuidarte y cómo hacerlo sin culpa.",
    expertId: "exp-psico",
    specialty: "Psicología clínica",
    category: "autoestima",
    videoId: "t-auto",
    durationMin: 38,
    access: "member",
    featured: true,
    publishedAt: "2026-08-22",
  },
  {
    id: "talk-finanzas",
    slug: "tu-dinero-en-paz",
    title: "Tu dinero en paz",
    description: "Presupuesto realista, fondo de emergencia y cómo dejar de evitar tus números.",
    expertId: "exp-finanzas",
    specialty: "Finanzas personales",
    category: "finanzas",
    videoId: "t-fin",
    durationMin: 45,
    access: "member",
    publishedAt: "2026-08-05",
  },
  {
    id: "talk-sueno",
    slug: "dormir-mejor",
    title: "Dormir mejor sin apps ni suplementos",
    description: "Higiene del sueño explicada simple: luz, horarios, cafeína y rituales que funcionan.",
    expertId: "exp-psico",
    specialty: "Psicología clínica",
    category: "sueno",
    videoId: "t-sueno",
    durationMin: 35,
    access: "free",
    publishedAt: "2026-07-18",
  },
  {
    id: "talk-habitos",
    slug: "habitos-en-la-vida-real",
    title: "Hábitos en la vida real",
    description: "Cómo sostener una rutina cuando tienes trabajo, casa y cero tiempo libre.",
    expertId: "sofi",
    specialty: "Bienestar",
    category: "habitos",
    videoId: "t-hab",
    durationMin: 40,
    access: "member",
    isNew: true,
    publishedAt: "2026-09-20",
  },
];

export const talkBySlug = (slug: string) => talks.find((t) => t.slug === slug);
